version: '3'

services: 
    leadmanager:
        container_name: leadmanager
        build: .
        volumes: 
            - .:/app
        ports: 
            - "8000:8000"
        command: python leadmanager/manage.py runserver 0.0.0.0:8000
        # command: ls -la

